FROM {{ namespace }}/murano-base:{{ tag }}
MAINTAINER {{ maintainer }}

RUN apt-get install -y --no-install-recommends \
        mysql-client \
        netcat-openbsd \
    && apt-get clean

USER murano
