FROM {{ image_spec("openstack-base") }}
MAINTAINER {{ maintainer }}

{{ copy_sources("openstack/murano", "/murano") }}

RUN useradd -U -m -d /var/lib/murano -G microservices murano \
    && chmod 755 /var/lib/murano \
    && /var/lib/microservices/venv/bin/pip install --upgrade /murano \
    && mkdir -p /etc/murano /var/lib/murano \
    && cp -r /murano/etc/murano/* /etc/murano/ \
    && chown -R murano: /etc/murano /var/lib/murano

